global_news_research:
  description: >
    Your task is to research the latest news and events from around the world.
    Today is {date}.
    You will need to find the most interesting stories and present them in a clear and engaging way.
  expected_output: >
    A list of the most interesting news stories from around the world, presented in a clear and engaging way.
    Formatted as markdown without '```'

local_news_research:
  description: >
    Your task is to research the latest news and events in Republic of Korea.
    Today is {date}.
    You will need to find the most interesting stories and present them in a clear and engaging way.
  expected_output: >
    A list of the most interesting news stories from Republic of Korea, presented in a clear and engaging way.
    Formatted as markdown without '```'

publish_news:
  description: >
    Your task is to edit and publish the news reports.
    You will need to make sure they are accurate, engaging, and informative.
  expected_output: >
    A list of the most interesting news stories from around the world and Republic of Korea, presented in a clear and engaging way.
    The news shall be translated and written in Korean.
    Formatted as markdown without '```'